//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Middleware
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiMonitorTB
    {
        public int Id { get; set; }
        public string Page { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string DeviceSRNO { get; set; }
        public string DeviceName { get; set; }
        public string Status { get; set; }
        public string Command { get; set; }
    }
}
