//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Middleware
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourierTB
    {
        public int Id { get; set; }
        public string CourierNo { get; set; }
        public string EmployeeName { get; set; }
        public string CourierCompany { get; set; }
        public string CourierPersonName { get; set; }
        public string Time { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Description { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    }
}
