//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Middleware
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevicesTB
    {
        public int DeviceId { get; set; }
        public string DeviceName { get; set; }
        public string DeviceSerialNo { get; set; }
        public string IPAddress { get; set; }
        public string DeviceStatus { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
        public string DeviceLocation { get; set; }
        public string DeviceAccountId { get; set; }
        public string DeviceDirection { get; set; }
        public string DeviceIPAddress { get; set; }
        public string Port { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}
