//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Middleware
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceLogsTB
    {
        public int LogId { get; set; }
        public Nullable<int> DeviceAccountId { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
        public Nullable<System.DateTime> AttendDate { get; set; }
        public string PunchStatus { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string AccessCardNo { get; set; }
        public Nullable<System.DateTime> ADate { get; set; }
        public Nullable<System.TimeSpan> ATime { get; set; }
    }
}
