//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Middleware
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeScheduledVisitTB
    {
        public int Id { get; set; }
        public Nullable<int> VisitId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    }
}
