//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Middleware
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePunchTB
    {
        public int Id { get; set; }
        public string major { get; set; }
        public string minor { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string employeeNoString { get; set; }
        public string cardNo { get; set; }
        public string cardReaderNo { get; set; }
        public string doorNo { get; set; }
        public string currentVerifyMode { get; set; }
        public string serialNo { get; set; }
        public string type { get; set; }
        public string mask { get; set; }
        public string name { get; set; }
        public string userType { get; set; }
        public string deviceIndex { get; set; }
        public string DeviceAccountId { get; set; }
    }
}
