//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Middleware
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailSettingTB
    {
        public int Id { get; set; }
        public string Host { get; set; }
        public string smtpfrom { get; set; }
        public Nullable<int> port { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    }
}
