//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Middleware
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTB
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public string Photo { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string UserType { get; set; }
        public string Company { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string EmpCode { get; set; }
        public string IdProof { get; set; }
        public string IdProofNumber { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public string CardNo { get; set; }
    }
}
