//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Middleware
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorTB
    {
        public int Id { get; set; }
        public string VisitorId { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string Contact { get; set; }
        public string Photo { get; set; }
        public string Company { get; set; }
    }
}
