//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.Middleware
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorEntryTB
    {
        public int Id { get; set; }
        public Nullable<int> VisitId { get; set; }
        public string VisitorId { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
        public string Address { get; set; }
        public string InTime { get; set; }
        public string OutTime { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string EmailId { get; set; }
        public string Contact { get; set; }
        public string Purpose { get; set; }
        public string Remark { get; set; }
        public string Priority { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string IdProof { get; set; }
        public string IdProofNumber { get; set; }
        public string Photo { get; set; }
        public string Material { get; set; }
        public string VehicleNo { get; set; }
        public string VehicleType { get; set; }
        public string VehiclePUCNo { get; set; }
        public Nullable<System.DateTime> PUCEndDate { get; set; }
        public string VisitorType { get; set; }
        public string DeviceName { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public string CardNo { get; set; }
    }
}
